# Configuration for rustfmt
edition = "2021"
version = "current"
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
merge_derives = true
use_try_shorthand = false
force_explicit_abi = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false
imports_layout = "Mixed"
empty_line_end_of_file = true
newline_end_of_file = true
format_code_in_doc = true
overflow_delimited_expr = true
enum_discrim_align_threshold = 20
condense_wildcard_suffixes = true
combine_control_expr = true
imports_granularity = "Crate"
fn_args_density = "Tall"
type_layout = "Tight"
use_field_init_shorthand = true
force_multiline_fields = false
fn_return_style = "Auto"
opt_type_alignment = false
control_brace_style = "AlwaysSameLine"
trailing_separator = "Never"
trailing_comma = "Vertical"
match_block_trailing_comma = true
force_explicit_unchecked = false
max_width = 100
use_try_shorthand = false
