apiVersion: v1
kind: Service
metadata:
  name: {{ include "hwp-agent.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "hwp-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 50052
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "hwp-agent.selectorLabels" . | nindent 4 }}
